### ISSUE TITLE
Add practice exercises for #48in24

### ISSUE THREAD

**Issue by BNAndras** [exercism/d#214]
@ErikSchierboom, I've got the D compiler working on my other computer. As a heads-up, I've got a few exercises I'm looking at adding in the next few weeks.

- [x] acronym
- [ ] list-ops
- [x] protein-translation
- [x] allergies
- [x] eliuds-eggs
- [x] scrabble-score
- [x] sieve
- [x] space-age

**Comment by ErikSchierboom** [comment]
Great!

**Comment by ErikSchierboom** [comment]
I've added you to the D team
