### ISSUE TITLE
README.md in several exercises points to dead link

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/d#56]
In many of the exercise `README.md`, the line "Make sure you have read D Page" points the user to http://exercism.io/languages/dlang, which is the 404 page for exercism. These links should instead point to http://exercism.io/languages/d. I believe this is caused by the fact that `docs/EXERCISE_README_INSERT.md` also has the issue.

A list of effected exercises are:
- [ ] bob
- [ ] circular-buffer
- [ ] crypto-square
- [ ] difference-of-squares
- [ ] etl
- [ ] gigasecond
- [ ] hamming
- [ ] hello-world
- [ ] leap
- [ ] nucleotide-count
- [ ] pangram
- [ ] raindrops
- [ ] react
- [ ] rna-transcription
- [ ] robot-name
- [ ] roman-numerals
- [ ] series
- [ ] triangle

**Comment by kytrinyx** [comment]
I see that you got this one fixed. Thanks so much for tackling that!
